internal_storage: true
internal_prestocked: 
    - MUSIC_DISC_11
    - MUSIC_DISC_13
    - MUSIC_DISC_BLOCKS
    - MUSIC_DISC_CAT
    - MUSIC_DISC_CHIRP
    - MUSIC_DISC_FAR
    - MUSIC_DISC_MALL
    - MUSIC_DISC_MELLOHI
    - MUSIC_DISC_STAL
    - MUSIC_DISC_STRAD
    - MUSIC_DISC_WAIT
    - MUSIC_DISC_WARD
distance: 64
auto_save_secs: 600
verbose_logging: true
debug_logging: true